routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['admin']], function () {

    Route::get('/', function () {
        return view('home');
    });
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', UserController::class);
    Route::get('approved/{user}', [UserController::class, 'approved'])->name('approved');
    Route::get('reject/{user}', [UserController::class, 'reject'])->name('rejected');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'username',
        'bio',
        'location',
        'website',
        'online',
        'two_step_sms',
        'two_step_face',
        'phone',
        'date_of_birth',
        'gender_id',
        'last_seen',
        'verify',
        'subscription_price',
        'balance',
        'country',
        'code'
    ];
    const VERIFY_PENDING = 1;
    const VERIFY = 2;
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function photo()
    {
        return $this->morphOne(File::class, 'fileable')->where('type', File::FILE_PHOTO);
    }

    public function banner()
    {
        return $this->morphOne(File::class, 'fileable')->where('type', File::FILE_BANNER);
    }

    public function post()
    {
        return $this->hasMany(Post::class);
    }

    public function postAsc()
    {
        return $this->hasMany(Post::class)->orderBy('id', 'asc');
    }

    public function postDesc()
    {
        return $this->hasMany(Post::class)->orderBy('id', 'desc');
    }

    public function postAscLikes()
    {
        return $this->hasMany(Post::class)->orderBy('likes', 'asc');
    }

    public function postDescLikes()
    {
        return $this->hasMany(Post::class)->orderBy('likes', 'desc');
    }

    public function options()
    {
        return $this->belongsToMany(Option::class);
    }

    public function notifications()
    {
        return $this->hasOne(Settings::class, 'user_id');
    }

    public function bookmarks()
    {
        return $this->belongsToMany(Post::class, 'bookmarks', 'user_id', 'post_id')->orderBy('bookmarks.id', 'desc');
    }

    public function bookmarksAll()
    {
        return $this->belongsToMany(Post::class, 'bookmarks', 'user_id', 'post_id');
    }

    public function customlist()
    {
        return $this->morphMany(CustomList::class, 'customlistable')->where('type', CustomList::TYPE_USER);
    }

    public function subscriber()
    {
        return $this->hasMany(Network::class, 'subscriber_id');
    }

    public function restricted()
    {
        return $this->hasMany(Restricted::class, 'initiator_id');
    }

    public function blacklist()
    {
        return $this->hasMany(Blacklist::class, 'initiator_id');
    }

    public function lists()
    {
        return $this->hasMany(Lists::class, 'user_id');
    }

    public function loginSession()
    {
        return $this->hasMany(LoginSession::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function answer_comments()
    {
        return $this->hasMany(CommentAnswer::class);
    }

    public function reactions()
    {
        return $this->hasMany(Reaction::class);
    }

    public function gender()
    {
        return $this->belongsTo(Gender::class);
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function report()
    {
        return $this->morphMany(Report::class, 'reportable');
    }

    public function rooms()
    {
        return $this->belongsToMany(Room::class, 'room_users');
    }

    public function messages()
    {
        return $this->hasMany(Message::class, 'sender_id');
    }

    public function mute()
    {
        return $this->hasMany(MuteChat::class, 'sender_id');
    }

    public function subscriptions()
    {
        return $this->hasMany(Subscription::class);
    }

    public function promotions()
    {
        return $this->hasMany(Promotion::class);
    }

    public function promotion()
    {
        return $this->hasOne(Promotion::class);
    }

    public function verification()
    {
        return $this->hasMany(UserVerification::class);
    }

    public function userSubscription()
    {
        return $this->hasMany(UserSubscription::class);
    }

    public function customer()
    {
        return $this->hasOne(UserCard::class);
    }

    public function paymentable()
    {
        return $this->morphOne(Payment::class, 'paymentable')->latest();
    }

    public function bundles()
    {
        return $this->hasMany(Bundle::class);
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\File;
use App\Models\User;
use App\Models\UserVerification;
use Illuminate\Http\Request;
use Storage;
class UserController extends Controller
{
    public function index()
    {
        $users = User::where('verify', User::VERIFY_PENDING)->simplePaginate(10);
        return view('users.index', compact('users'));
    }

    public function show(User $user)
    {
        $ids = UserVerification::where('user_id', $user->id)->pluck('id');
        $photos = File::where('type', File::FILE_DOCUMENT)->whereIn('fileable_id', $ids)->get();
        return view('users.photos', compact('photos', 'user'));
    }

    public function approved(User $user)
    {
        $user->update(['verify' => User::VERIFY]);
        return redirect()->route('users.index');
    }

    public function reject(User $user)
    {
        $user->update(['verify' => 0]);
        $files = Storage::allFiles('public/user-docs/' . $user->id . '/');
        if ($files) {
            Storage::delete($files);
            $ids = UserVerification::where('user_id', $user->id)->pluck('id');
            File::where('type', File::FILE_DOCUMENT)->whereIn('fileable_id', $ids)->delete();
        }
        return redirect()->route('users.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\AvatarRequest;
use App\Http\Requests\User\BannerRequest;
use App\Http\Requests\User\ChangePasswordRequest;
use App\Http\Requests\User\CheckCodePhoneRequest;
use App\Http\Requests\User\CheckCodeRequest;
use App\Http\Requests\User\ForgotPasswordRequest;
use App\Http\Requests\User\OnlineRequest;
use App\Http\Requests\User\PhoneRequest;
use App\Http\Requests\User\TwoAuthRequest;
use App\Http\Requests\User\UpdateRequest;
use App\Http\Requests\User\UsernameRequest;
use App\Http\Requests\Verification\VerificationRequest;
use App\Http\Resources\Bundle\DataResource;
use App\Http\Resources\User\UserResource;
use App\Http\Traits\SmsTrait;
use App\Models\Document;
use App\Models\Gender;
use App\Models\User;
use App\Models\UserCard;
use App\Models\UserPhone;
use App\Models\Verification;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Storage;
use DB;
use App\Models\File;
use App\Facades\Base64;
use Illuminate\Support\Facades\Mail;
use App\Http\Resources\Collection;
use JWTAuth;
use Illuminate\Http\File as Files;

class UserController extends ApiController
{
    use SmsTrait;

    /**
     * update user profile
     *
     * @param UpdateRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(UpdateRequest $request)
    {
        $user = auth()->user();
        $user->update($request->validated());
        return $this->respondSuccess(new UserResource($user));
    }

    /**
     *  Upload a avatar
     *
     * @param AvatarRequest $request
     * @return \Illuminate\Http\JsonResponse
     */

    public function avatar(AvatarRequest $request)
    {
        DB::beginTransaction();
        $path = 'public/user/' . auth()->id() . '/';
        $avatar = auth()->user()->photo;
        if ($avatar) {
            Storage::delete($avatar->path . $avatar->name);
            auth()->user()->photo()->delete();
        }

        $fileData = Base64::save($request->input('photo'), $path);
        if (is_array($fileData)) {
            auth()->user()->photo()->create([
                'name' => $fileData['name'],
                'path' => $fileData['path'],
                'type' => File::FILE_PHOTO,
            ]);
        } else {
            return $this->respondWithError('File upload error');
        }
        DB::commit();
        return $this->respondSuccess(new UserResource(auth()->user()));
    }

    /**
     * upload banner
     *
     * @param BannerRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function banner(BannerRequest $request)
    {
        DB::beginTransaction();
        $path = 'public/user-banner/' . auth()->id() . '/';
        $banner = auth()->user()->banner;
        if ($banner) {
            Storage::delete($banner->path . $banner->name);
            auth()->user()->banner()->delete();
        }

        $fileData = Base64::save($request->input('banner'), $path);
        if (is_array($fileData)) {
            auth()->user()->banner()->create([
                'name' => $fileData['name'],
                'path' => $fileData['path'],
                'type' => File::FILE_BANNER,
            ]);
        } else {
            return $this->respondWithError('File upload error');
        }
        DB::commit();
        return $this->respondSuccess(new UserResource(auth()->user()));
    }

    /**
     * profile a user
     *
     * @param User $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function profile(User $user)
    {
        return $this->respondSuccess(new UserResource($user));
    }

    /**
     * my profile
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function myProfile()
    {
        return $this->respondSuccess(new UserResource(auth()->user()));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function search(Request $request)
    {
        $currentUser = auth()->user();
        $user = User::where('username', "LIKE", "$request->username%")->where('id', '!=', $currentUser->id)->get()->take(5);
        return $this->respondSuccess(new Collection(UserResource::collection($user)));
    }

    /**
     * update a status
     *
     * @param OnlineRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function online(OnlineRequest $request)
    {
        $user = auth()->user();
        if ($request->online == 1) {
            $user->update(['last_seen' => null]);
        } else {
            $user->update(['last_seen' => Carbon::now()->format('Y-m-d H:i:s')]);
        }
        $user->update($request->validated());
        return $this->respondSuccess(new UserResource($user));
    }

    /**
     * delete a photo
     * @return \Illuminate\Http\JsonResponse
     */
    public function deletePhoto()
    {
        DB::beginTransaction();
        $path = 'public/user/' . auth()->id() . '/';
        $files = Storage::allFiles($path);
        if ($files) {
            Storage::delete($files);
            auth()->user()->photo()->delete();
        }
        DB::commit();
        return $this->respondSuccess(new UserResource(auth()->user()));
    }

    public function forgotPassword(ForgotPasswordRequest $request)
    {
        $user = User::where('email', $request->search)->orWhere('username', $request->search)->first();
        if (is_null($user)) {
            return $this->respondNotFound('User not found');
        } else {
            $new_password = rand(00000000, 99999999);
            $user->update(['password' => Hash::make($new_password)]);
            Mail::send('mail.forgot-password', compact('new_password'), function ($message) use ($user) {
                $message->to("$user->email")
                    ->subject('New password');
            });
            return $this->respondSuccess($user);
        }

    }

    /**
     * change a password
     *
     * @param ChangePasswordRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function changePassword(ChangePasswordRequest $request)
    {
        $user = auth()->user();
        $user->update(['password' => Hash::make($request->new_password)]);
        return $this->respondSuccess($user);

    }

    /**on\off a two step auth
     *
     * @param TwoAuthRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function twoStepAuth(TwoAuthRequest $request)
    {
        $user = auth()->user();
        if (is_null($user->phone) && $request->two_step_sms == 1) {
            return $this->respondValidationError('Add your phone number to your profile', 422);
        }
        $user->update($request->validated());
        return $this->respondSuccess(new UserResource($user));
    }

    /**
     * verify code two step auth
     *
     * @param CheckCodeRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function verifyCode(CheckCodeRequest $request)
    {
        $requestPhone = $request->phone;
        $requestCode = $request->code;
        $checkVerification = Verification::where('phone', $requestPhone)->exists();
        if (!$checkVerification) {
            return response()->json(['message' => 'Phone not found'], 404);
        }
        $verification = Verification::where('phone', $requestPhone)->first();
        $check = $this->checkCode($requestCode, $verification->code, $requestPhone, $verification->phone, $request);
        return $check;
    }


    /**
     * check username
     *
     * @param UsernameRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function checkUsername(UsernameRequest $request)
    {
        $check = User::where('username', $request->username)->exists();
        if (!$check) {
            return $this->respondSuccess(true);
        } else {
            return $this->respondSuccess(false);
        }
    }

    /**
     * check phone
     *
     * @param PhoneRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function checkPhone(PhoneRequest $request)
    {
        $check = User::where('phone', $request->phone)->exists();
        if (!$check) {
            return $this->respondSuccess(true);
        } else {
            return $this->respondSuccess(false);
        }
    }

    /**
     * send code
     *
     * @param $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function updatePhone(PhoneRequest $request)
    {
        $user = auth()->user();
        $phone = $request->phone;
        if ($phone == null) {
            return response()->json(['message' => 'Phone not found'], 404);
        }
        $code = $this->generateCode();
        UserPhone::updateOrCreate(['phone' => $phone], [
            'code' => $code,
            'user_id' => $user->id,
            'codeCountry' => $request->codeCountry,
            'country' => $request->country
        ]);
        $send = $this->sendSms($phone, $code);
        return $send;
    }

    public function verifyCodePhone(CheckCodePhoneRequest $request)
    {
        $user = auth()->user();
        $requestPhone = $request->phone;
        $requestCode = $request->code;
        $checkVerification = UserPhone::where('phone', $requestPhone)->where('user_id', $user->id)->exists();
        if (!$checkVerification) {
            return response()->json(['message' => 'Phone not found'], 404);
        }
        $verification = UserPhone::where('phone', $requestPhone)->where('user_id', $user->id)->first();
        $check = $this->checkCodePhone($requestCode, $verification->code, $requestPhone, $verification->phone, $user);
        return $check;
    }

    public function genders()
    {
        return $this->respondSuccess(Gender::all());
    }

    public function documents()
    {
        return $this->respondSuccess(Document::all());
    }

    public function verify(VerificationRequest $request)
    {

resources/views/users/index.blade.php
@extends('layouts.app') @section('content')



    <div class="panel panel-default" style="text-align: center; margin: auto; width: 90% ">

        <p></p>
        <p></p>
        <div class="panel-body">
            <table class="table table-bordered table-responsive table-striped">
                <tr>
                    <th width="1%">id</th>
                    <th width="1%">Name</th>
                    <th width="1%">Username</th>
                    <th width="1%">E-mail</th>
                    <th width="1%">phone</th>
                    <th width="1%">Action</th>
                </tr>
                <tr>
                    <td colspan="13" class="light-green-background no-padding" title="Create new template">
                        <div class="row centered-child">
                            <div class="col-md-20">
                            </div>
                        </div>
                    </td>
                </tr>
                @foreach($users as $model)
                    <tr>
                        <td>{{$model->id}}</td>
                        <td>{{$model->name}}</td>
                        <td>{{$model->username}}</td>
                        <td>{{$model->email}}</td>
                        <td>{{$model->phone}}</td>
                        <td style="text-align: left">

{{--                            {{Form::open(['class' => 'confirm-delete', 'route' => ['courier.destroy', $model->id], 'method' => 'DELETE'])}}--}}
{{----}}
                            {{ link_to_route('users.show', 'View', [$model->id], ['class' => 'btn btn-success btn-xs']) }}
{{--                            {{Form::button('Удалить', ['class' => 'btn btn-danger btn-xs', 'type' => 'submit'])}} {{Form::close()}}--}}
{{--                            {{Form::close()}}--}}
                        </td>
                    </tr>
                @endforeach

            </table>
            {{$users->links()}}
        </div>
    </div>
@endsection

resources/views/users/photos.blade.php
@extends('layouts.app') @section('content')

    <div class="panel panel-default" style="text-align: center; margin: auto; width: 90% ">

        <p></p>
        <p></p>
        <div class="panel-body">
            <table class="table table-bordered table-responsive table-striped">
                <tr>
{{--                    <th width="1%">id</th>--}}
                    <th width="1%">Photo</th>
{{--                    <th width="1%">Action</th>--}}
                </tr>
                <tr>
                    <td colspan="13" class="light-green-background no-padding" title="Create new template">
                        <div class="row centered-child">
                            <div class="col-md-20">
                            </div>
                        </div>
                    </td>
                </tr>
                @foreach($photos as $model)
                    <tr>
{{--                        <td>{{$model->id}}</td>--}}
                        <td><img src="{{url(\Illuminate\Support\Facades\Storage::url($model->path . $model->name))}}"  class="scale" width="250px" height="300"></td>
{{--                        <td ><img src="https://fizl.semper.team/storage/user/1/1640094862811972.png" class="scale" width="500px" height="500px"></td>--}}

{{--                        <td style="text-align: left">--}}

                            {{--                            {{Form::open(['class' => 'confirm-delete', 'route' => ['courier.destroy', $model->id], 'method' => 'DELETE'])}}--}}
                            {{----}}
                            {{--                            {{ link_to_route('courier.edit', 'Редактировать', [$model->id], ['class' => 'btn btn-success btn-xs']) }}--}}
                            {{--                            {{Form::button('Удалить', ['class' => 'btn btn-danger btn-xs', 'type' => 'submit'])}} {{Form::close()}}--}}
                            {{--                            {{Form::close()}}--}}
{{--                        </td>--}}
                    </tr>
                @endforeach
            </table>
            {{ link_to_route('approved', 'Approved', [$user->id],['class' => 'btn btn-success btn-xs']) }}
            {{ link_to_route('rejected', 'Rejected', [$user->id],['class' => 'btn btn-danger btn-xs']) }}

        </div>
    </div>
@endsection